# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{scoped_by_domain}
  s.version = "0.1.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Josh N. Abbott"]
  s.date = %q{2010-03-15}
  s.description = %q{Use this gem to scope active record attribute values by specific domains. EG: is_active returns `true` at oakley.com, but `false` at oakley.ca.}
  s.email = %q{joshnabbott@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "init.rb",
     "lib/scoped_by_domain.rb",
     "rails/init.rb",
     "scoped_by_domain.gemspec",
     "spec/scoped_by_domain_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/joshnabbott/scoped_by_domain}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Gem provides domain-scoping capability to your model attributes.}
  s.test_files = [
    "spec/scoped_by_domain_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_runtime_dependency(%q<activerecord>, [">= 2.3.4"])
      s.add_runtime_dependency(%q<better_delegation>, [">= 1.0.0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<activerecord>, [">= 2.3.4"])
      s.add_dependency(%q<better_delegation>, [">= 1.0.0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<activerecord>, [">= 2.3.4"])
    s.add_dependency(%q<better_delegation>, [">= 1.0.0"])
  end
end

